#100% tested by kaushik Patel with Gitlab and AWS CodeDeploy
variables:
  S3_BUCKET_NAME: "my-bucket-name"

deploy:
  stage: deploy
  image: kenp8036/awscli2kp
  script:
    - zip test.zip -r . -x \*.git\* -x .gitlab-ci.yml -x my_app.sh
    - aws s3 mv ./test.zip s3://$S3_BUCKET_NAME
  only:
    - master
